### ISSUE TITLE
ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)

### ISSUE THREAD

**Issue by Krishnarohith10** [Krishnarohith10/OneHotEncoder#1]
![2](https://user-images.githubusercontent.com/44919399/71778123-8edff880-2fcf-11ea-8d7e-9d528e9f7912.jpg)
**I have run this code then this says**
![1](https://user-images.githubusercontent.com/44919399/71778126-a0290500-2fcf-11ea-809b-97924f73dcfd.jpg)
I don't know what to say. can someone help with this?

**Comment by ScarletMcLearn** [comment]
Same here

**Comment by Krishnarohith10** [comment]
`from sklearn.preprocessing import LabelEncoder, OneHotEncoder`
`le = LabelEncoder()`
`X[:,3] = le.fit_transform(X[:,3])`
`ohe = OneHotEncoder()`
'res = ohe.fit_transform(X[:,3])'
'print(res.toarray())'

The issue is solved!
